---
apiVersion: v1
kind: Template
labels:
  build: "${REPO_NAME}-logapp"
  template: "${REPO_NAME}-logapp-bc-template"
metadata:
  name: "${REPO_NAME}-logapp-bc"
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      name: "${REPO_NAME}-logapp"
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      name: "${REPO_NAME}-logapp-${JOB_NAME}"
    spec:
      completionDeadlineSeconds: 600
      failedBuildsHistoryLimit: 3
      nodeSelector:
      output:
        to:
          kind: ImageStreamTag
          name: "${REPO_NAME}-logapp:latest"
      postCommit: {}
      runPolicy: SerialLatestOnly
      source:
        git:
          ref: "${SOURCE_REPO_REF}"
          uri: "${SOURCE_REPO_URL}"
        type: Git
      strategy:
        dockerStrategy:
        type: Docker
      successfulBuildsHistoryLimit: 3
parameters:
  - name: REPO_NAME
    description: Application repository name
    displayName: Repository Name
    required: true
  - name: JOB_NAME
    description: Job identifier (i.e. 'pr-5' OR 'master')
    displayName: Job Branch Name
    required: true
  - name: SOURCE_REPO_REF
    description: Git Pull Request Reference (i.e. 'pull/CHANGE_ID/head')
    displayName: Source Repository Reference
    required: true
  - name: SOURCE_REPO_URL
    description: Git Repository URL
    displayName: Source Repository URL
    required: true
